on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Use packj.dev
        uses: ossillate-inc/packj.dev@main
